<#import "parts/common.ftlh" as c>

<@c.page>
    <h5>Hello, guest</h5>
    <head>This a simple Pet Project :) </head>
    <br><br>

    <a href="/registration"
       class="btn btn-light"> Registration page
    </a>

    <br><br>
    <a href="/login"
       class="btn btn-light"> Login page
    </a>

    <br><br>
    <a href="/main"
       class="btn btn-light"> Main page
    </a>
    <br><br>
    <a href="/messages"
       class="btn btn-light"> Messages
    </a>
</@c.page>